FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libsdl2-dev libglew-dev build-essential pkg-config libstb-dev

COPY . /repo
WORKDIR /repo
RUN gcc -o pl_mpeg_extract_frames pl_mpeg_extract_frames.c $(pkg-config --cflags --libs sdl2 glew ) -I/usr/include/stb

FROM ubuntu:20.04 as package
COPY --from=builder /repo/pl_mpeg_extract_frames /
